name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}' # 在 GitHub secrets 中配置 GCP 服务账号密钥

      - name: Deploy Function
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: app-store-webhook-forwarder # 函数名称
          runtime: python312
          entry_point: webhook_handler
          env_vars: |
            LARK_WEBHOOK_URL=${{ secrets.LARK_WEBHOOK_URL }}
            LARK_SIGNING_SECRET=${{ secrets.LARK_SIGNING_SECRET }}
            APP_STORE_CONNECT_SECRET=${{ secrets.APP_STORE_CONNECT_SECRET }}
